[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# foundry.toml
 
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

[rpc_endpoints]
anvil = "http://localhost:8545"
base_sepolia = "${BASE_SEPOLIA_RPC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
